version: "3.9"

services:
  flask_app:
    container_name: flask_app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    environment:
      - DB_URL=postgresql://postgres:Ertoshka0508@flask_db:5432/db
      - PYTHONPATH=/app
    depends_on:
      - flask_db
    volumes:
      - .:/app

  flask_db:
    container_name: flask_db
    image: postgres:12
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=Ertoshka0508
      - POSTGRES_USER=postgres
      - POSTGRES_DB=db
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}
